// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's PredictEsport profile and premium access status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: premium, error: prErr }] = await Promise.all([
      supabase.from("profiles").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("premium_users").select("*").eq("user_id", userId).maybeSingle()
    ]);
    if (pErr || prErr) {
      return {
        content: [{ type: "text", text: (pErr ?? prErr).message }],
        isError: true
      };
    }
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      profile: profile ?? null,
      is_premium: !!premium,
      premium_source: premium ? "manual" : "stripe_or_none"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_reviews_default = defineTool2({
  name: "list_reviews",
  title: "List approved reviews",
  description: "List approved public reviews of PredictEsport, most recent first.",
  inputSchema: {
    limit: z.number().int().default(20).describe("Maximum number of reviews to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser2(ctx).from("reviews").select("id, author_name, rating, content, created_at").eq("is_approved", true).order("created_at", { ascending: false }).limit(capped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-review.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var submit_review_default = defineTool3({
  name: "submit_review",
  title: "Submit a review",
  description: "Submit a new PredictEsport review as the signed-in user. The review is created unapproved and must be approved by an admin before appearing publicly.",
  inputSchema: {
    author_name: z2.string().trim().min(2).max(100).describe("Display name shown with the review."),
    rating: z2.number().int().min(1).max(5).describe("Star rating from 1 to 5."),
    content: z2.string().trim().min(5).max(2e3).describe("Review text.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ author_name, rating, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("reviews").insert({
      user_id: ctx.getUserId(),
      author_name,
      rating,
      content,
      is_approved: false
    }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: "Review submitted and pending approval."
        }
      ],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-matches.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var CSV_URL = "https://raw.githubusercontent.com/franc0510/streamlit-shine-sparkle/main/schedule_with_probs.csv";
function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return [];
  const headers = lines[0].split(",").map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const cells = line.split(",");
    const row = {};
    headers.forEach((h, i) => {
      row[h] = (cells[i] ?? "").trim();
    });
    return row;
  });
}
var list_upcoming_matches_default = defineTool4({
  name: "list_upcoming_matches",
  title: "List upcoming LoL matches",
  description: "List upcoming League of Legends matches with PredictEsport win probabilities. Returns tournament, date, teams, and BO1 win probabilities for each side.",
  inputSchema: {
    limit: z3.number().int().default(10).describe("Maximum number of matches to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const capped = Math.min(Math.max(limit ?? 10, 1), 50);
    const res = await fetch(`${CSV_URL}?t=${Date.now()}`);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch schedule: ${res.status}` }],
        isError: true
      };
    }
    const rows = parseCsv(await res.text()).slice(0, capped);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { matches: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "obivwrnbupnbcqzxvztp";
var mcp_default = defineMcp({
  name: "predictesport-mcp",
  title: "PredictEsport MCP",
  version: "0.1.0",
  instructions: "PredictEsport tools. Use `list_upcoming_matches` for upcoming League of Legends matches with ML win probabilities, `get_my_profile` to check the signed-in user's premium status, `list_reviews` to read approved public reviews, and `submit_review` to submit a new review pending moderation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_reviews_default,
    submit_review_default,
    list_upcoming_matches_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
